services:
    postgres:
        image: postgres:14.1-alpine
        container_name: transfer_db
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
        ports:
            - 5432:5432
        volumes:
            - ./db/postgres-data:/var/lib/postgresql/data
            - ./db/init:/docker-entrypoint-initdb.d
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: gfw1994@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - 82:80
        depends_on:
            - postgres
        volumes:
            - ./db/pgadmin_data:/var/lib/pgadmin
    rabbitmq:
        image: rabbitmq:4-management
        container_name: rabbitmq
        hostname: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
            - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf