spring:
  application:
    name: sboot-transfer
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  rabbitmq:
    host: localhost
    virtualhost: /
    port: 5672
    username: admin
    password: 123